/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_malinkang_jnisample_JniUtil */

#ifndef _Included_com_malinkang_jnisample_JniUtil
#define _Included_com_malinkang_jnisample_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_malinkang_jnisample_JniUtil
 * Method:    sayHi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_malinkang_jnisample_JniUtil_sayHi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
